<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="33021" started-at="2018-04-08T11:18:41Z" finished-at="2018-04-08T11:19:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="33021" started-at="2018-04-08T11:18:41Z" finished-at="2018-04-08T11:19:14Z">
      <class name="com.logiceinvoice.scripts.TestCreateCustomer">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.logiceinvoice.scripts.TestCreateCustomer@735b478]" name="openApplication" is-config="true" duration-ms="21074" started-at="2018-04-08T16:48:41Z" finished-at="2018-04-08T16:49:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testCreateCustomer()[pri:0, instance:com.logiceinvoice.scripts.TestCreateCustomer@735b478]" name="testCreateCustomer" duration-ms="10423" started-at="2018-04-08T16:49:02Z" finished-at="2018-04-08T16:49:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.logiceinvoice.scripts.TestCreateCustomer.testCreateCustomer(TestCreateCustomer.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCustomer -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:com.logiceinvoice.scripts.TestCreateCustomer@735b478]" name="closeApplication" is-config="true" duration-ms="1470" started-at="2018-04-08T16:49:12Z" finished-at="2018-04-08T16:49:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCreateCustomer status=FAILURE method=TestCreateCustomer.testCreateCustomer()[pri:0, instance:com.logiceinvoice.scripts.TestCreateCustomer@735b478] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.logiceinvoice.scripts.TestCreateCustomer -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
